#!/bin/bash

# Tokyo Night themed borders
# Style options: round, square, uniform
# Color format: 0xAARRGGBB (A=alpha, R=red, G=green, B=blue)

options=(
    style=round
    width=4.0
    hidpi=on
    active_color=0xffc0caf5
    inactive_color=0xff414868
    # Additional options available:
    # background_color=0x00000000
    # ax_focus=on
    # blacklist="App1,App2"
    # whitelist="App1,App2"
)

borders "${options[@]}"
