#!/bin/bash
# scripts/installs/install_window_manager.sh
#
# Purpose:
#   Brings up the AeroSpace + SketchyBar + JankyBorders stack so it
#   starts at login and survives reboots.
#
# Architecture (matches the existing user setup, see configs/aerospace/aerospace.toml):
#   - AeroSpace launches itself at login (`start-at-login = true`)
#   - AeroSpace's `after-startup-command` runs sketchybar and borders for us,
#     then applies the per-monitor gaps via `apply-display-profile.sh`
#
#   So the "service management" we need is just:
#     1. Make sure AeroSpace is running (it will start the others)
#
#   We deliberately do NOT use `brew services start` for sketchybar/borders.
#   That would race against AeroSpace's own startup command and leave
#   them flapping in an "error" state in brew services list.
#
# Idempotent: process and launchctl checks short-circuit when already up.

set -e

# shellcheck source=/dev/null
source "$INSTALLS/helper_prompt.sh"

# --- 1. AeroSpace -------------------------------------------------------
# AeroSpace is a regular .app installed via brew cask. Launching it once
# is enough — `start-at-login = true` in aerospace.toml takes care of
# every subsequent boot.
log_step "AeroSpace"
if pgrep -xq AeroSpace; then
    log_ok "AeroSpace already running"
else
    if [[ ! -d "/Applications/AeroSpace.app" ]]; then
        log_err "AeroSpace.app missing in /Applications — was install_brew.sh run?"
        exit 1
    fi
    log_wait "Launching AeroSpace.app for the first time ..."
    open -a AeroSpace
    # Give it a moment to come up + run after-startup-command (sketchybar, borders).
    sleep 3
    log_ok "AeroSpace launched (menu-bar icon should appear)"
fi

# --- 2. Sketchybar + Borders (sanity check) -----------------------------
# AeroSpace's after-startup-command launches these. We just verify they
# came up — if they didn't, something is wrong with the aerospace config.
log_step "SketchyBar / Borders (launched by AeroSpace)"
if pgrep -xq sketchybar; then
    log_ok "sketchybar running"
else
    log_err "sketchybar NOT running — check aerospace.toml after-startup-command"
fi
if pgrep -xq borders; then
    log_ok "borders running"
else
    log_err "borders NOT running — check aerospace.toml after-startup-command"
fi

# Note: the stack has no LaunchAgent of its own. The per-monitor gaps + the
# workspace 7-9 assignment are generated by aerospace.toml's startup
# `apply-display-profile.sh` call, i.e. on every AeroSpace (re)start.

log_ok "Window-manager stack up"
